<?php

namespace app\admin\validate;

class ConfigMessageValidate extends \think\Validate
{
	protected $rule = ["type" => "require|max:50", "accesskeyid" => "require|max:100", "accesskeysecret" => "require|max:100", "signature" => "require|max:50", "interaccesskeyid" => "require|max:50", "interaccesskeysecret" => "require|max:100", "intersignature" => "require|max:50", "submail_appid" => "require|max:50", "submail_appkey" => "require|max:100", "submail_signname" => "require|max:50", "submail_interappid" => "require|max:50", "submail_interappkey" => "require|max:100", "submail_intersignname" => "require|max:50", "range_type" => "require|in:0,1,2|max:50", "title" => "require|max:30", "content" => "require|max:500", "remark" => "require|max:100"];
	protected $message = ["type.require" => "{%MOBILE_TYPE_REQUIRE}", "type.max" => "{%MOBILE_TYPE_MAX}", "accesskeyid.require" => "{%MOBILE_ALIYUN_ACCESSKEYID_REQUIRE}", "accesskeyid.max" => "{%MOBILE_ALIYUN_ACCESSKEYID_MAX}", "accesskeysecret.require" => "{%MOBILE_ALIYUN_ACCESSKEYSECRET_REQUIRE}", "accesskeysecret.max" => "{%MOBILE_ALIYUN_ACCESSKEYSECRET_MAX}", "signature.require" => "{%MOBILE_ALIYUN_SIGNATURE_REQUIRE}", "signature.max" => "{%MOBILE_ALIYUN_SIGNATURE_MAX}", "interaccesskeyid.require" => "{%MOBILE_SUBMAIL_INTER_APPID_REQUIRE}", "interaccesskeyid.max" => "{%MOBILE_SUBMAIL_INTER_APPID_MAX}", "interaccesskeysecret.require" => "{%MOBILE_SUBMAIL_INTER_APPKEY_REQUIRE}", "interaccesskeysecret.max" => "{%MOBILE_SUBMAIL_INTER_APPKEY_MAX}", "intersignature.require" => "{%MOBILE_SUBMAIL_INTER_SIGNNAME_REQUIRE}", "intersignature.max" => "{%MOBILE_SUBMAIL_INTER_SIGNNAME_MAX}", "submail_appid.require" => "{%MOBILE_SUBMAIL_APPID_REQUIRE}", "submail_appid.max" => "{%MOBILE_SUBMAIL_APPID_MAX}", "submail_appkey.require" => "{%MOBILE_SUBMAIL_APPKEY_REQUIRE}", "submail_appkey.max" => "{%MOBILE_SUBMAIL_APPKEY_MAX}", "submail_signname.require" => "{%MOBILE_SUBMAIL_SIGN_NAME_REQUIRE}", "submail_signname.max" => "{%MOBILE_SUBMAIL_SIGN_NAME_MAX}", "submail_interappid.require" => "{%MOBILE_SUBMAIL_INTER_APPID_REQUIRE}", "submail_interappid.max" => "{%MOBILE_SUBMAIL_INTER_APPID_MAX}", "submail_interappkey.require" => "{%MOBILE_SUBMAIL_INTER_APPKEY_REQUIRE}", "submail_interappkey.max" => "{%MOBILE_SUBMAIL_INTER_APPKEY_MAX}", "submail_intersignname.require" => "{%MOBILE_SUBMAIL_INTER_SIGNNAME_REQUIRE}", "submail_intersignname.max" => "{%MOBILE_SUBMAIL_INTER_SIGNNAME_MAX}", "range_type.require" => "{%RANGE_TYPE_REQUIRE}", "range_type.max" => "{%RANGE_TYPE_MAX}", "title.require" => "{%MESSAGE_TITLE_REQUIRE}", "title.max" => "{%MESSAGE_TITLE_MAX}", "content.require" => "{%MESSAGE_CONTENT_REQUIRE}", "content.max" => "{%MESSAGE_CONTENT_MAX}", "sms_operator.require" => "{%MOBILE_TYPE_REQUIRE}", "sms_operator.max" => "{%MOBILE_TYPE_MAX}"];
	protected $scene = ["aliyun_mobile" => ["accesskeyid", "accesskeysecret", "signature"], "aliyun_international_mobile" => ["interaccesskeyid", "interaccesskeysecret", "intersignature"], "submail_mobile" => ["submail_appid", "submail_appkey", "submail_sign_name"], "submail_international_mobile" => ["submail_interappid", "submail_interappkey", "submail_intersignname"], "template_message" => ["range_type", "title", "content", "sms_operator", "remark"]];
}